import "./globals.css";
import { Berkshire_Swash, Roboto } from "next/font/google";

import { CartProvider } from "./components/Cart/CartContext";
import { Toaster } from "react-hot-toast";
import Header from "./components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const berkshire = Berkshire_Swash({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-berkshire",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  italic: ["0", "1"],
  display: "swap",
  variable: "--font-roboto",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${berkshire.variable}`}>
        <CartProvider>
          <Header />
          <Toaster />
          {children}
          {/* <Footer /> */}
        </CartProvider>
      </body>
    </html>
  );
}
